### ISSUE TITLE
Completing the information design model

### ISSUE THREAD

**Issue by Polewska** [BMD91/webapp22-BuiDuc#4]
While working on the information design model, I noticed that the Order table is missing the "date" when the order was made. If you agree, I will add this property to the table. 

I was also trying to determine the constraints for each property, and just wanted to ask you some questions : 
- are you shipping only to Vietnam or worldwide? That is because I wanted to add a constraint on the address, but if you are shipping worldwide I will probably be unable to do that since many countries have different rules on how they list an address. 
- Is there a minimum value for which a client may place an order? 
- does "size of vase" means a diameter? 
- can clients choose vases that they want or do you only allow them to buy vases that fit their plants? I ask this because I noticed that we have a "suitable vase" in the Plant table, however, when it comes to managing Orders this value seems to be irrelevant for this app since a client can buy any vase and this app is not meant to be shown to them. Therefore is this property only for your information?

**Comment by BMD91** [comment]
- Sure that you can add "Date of purchase" in the "Order" table. We forgot about that infor. Thanks for your advice!
- For simplicity of shipment, you can choose all delivered address in Germany or where you are familiar with. We need a test for this app, so that you must not to apply all shipment in Vietnam, because you do not know about that country.
- Customers can buy anything from our shop as they want without boundary.
- Sizes of vase can be named as "Small", "Medium", "Large" and "X-Large".
- Customers also can choose, which vases they want. Otherwise our employees will recommend, which vases are suitable for which plants. So that, it is optional choices when adding size of vase in "Order".

**Comment by Polewska** [comment]
Thank you for this very clear and helpful answer 👍 

If you don't mind I will add the constraint to the Date of purchase to assure that all of them are higher than 01.01.2022. Since that's the year when the app was created. This could however be changed in the future.

**Comment by BMD91** [comment]
Yes, you can create that constraint. In case it becomes complicated, you can delete that.

**Comment by Polewska** [comment]
Just letting you know, that I have now uploaded the first design model to the readme file. I however still have two issues with it 1. constraint on the delivery address and 2. saving the number of plants/vases added to the order. I will however think about it more and probably provide the solution tomorrow morning.
